Update process_pdf.yml

diff --git a/.github/workflows/process_pdf.yml b/.github/workflows/process_pdf.yml
--- a/.github/workflows/process_pdf.yml
+++ b/.github/workflows/process_pdf.yml
@@ -48,22 +48,22 @@ jobs:
           python -m pip install --upgrade pip
           pip install requests loguru fire lxml
 
-      - name: Verify Grobid Service
-        timeout-minutes: 5
-        run: |
-          echo "Waiting for Grobid to be ready..."
-          for i in {1..30}; do
-            if curl -sSf http://localhost:8070/api/isalive > /dev/null; then
-              echo "Grobid is ready!"
-              curl -v http://localhost:8070/api/version
-              exit 0
-            fi
-            echo "Attempt $i: Service not ready yet, waiting..."
-            sleep 10
-          done
-          echo "Grobid failed to start. Displaying logs:"
-          docker logs $(docker ps -q --filter ancestor=lfoppiano/grobid:latest-crf)
-          exit 1
+      # - name: Verify Grobid Service
+      #   timeout-minutes: 5
+      #   run: |
+      #     echo "Waiting for Grobid to be ready..."
+      #     for i in {1..30}; do
+      #       if curl -sSf http://localhost:8070/api/isalive > /dev/null; then
+      #         echo "Grobid is ready!"
+      #         curl -v http://localhost:8070/api/version
+      #         exit 0
+      #       fi
+      #       echo "Attempt $i: Service not ready yet, waiting..."
+      #       sleep 10
+      #     done
+      #     echo "Grobid failed to start. Displaying logs:"
+      #     docker logs $(docker ps -q --filter ancestor=lfoppiano/grobid:latest-crf)
+      #     exit 1
 
       - name: Process PDF
         run: python .github/scripts/process_pdf.py ${{ github.event.inputs.pdf_path }} --format ${{ github.event.inputs.output_format }}
